### ISSUE TITLE
Can't not handle Range "…"

### ISSUE THREAD

**Issue by mengzhuo** [cznic/ebnf2y#3]
"…" is supported in ebnf package for Range 
But ebnf2y can't not handle it

**Comment by cznic** [comment]
`...` in EBNF denotes character ranges, which is a concern of a lexer/tokenizer. `ebnf2y` generates parsers, not tokenizers.

**Comment by mengzhuo** [comment]
So... how can I generate pareser  like this ?
`NOSPCRLFCL =  "\x01" … "\x09" | "\x0B" …  "\x0C" | "\x0E"  …  "\x1F" |  "\x21"  …  "\x39" | "\x3B"  …  "\xFF" .`

**Comment by cznic** [comment]
That rule does not define anything a parser can do so you cannot. You can however use [`golex`](https://github.com/cznic/golex) to generate a tokenizer which recognizes the rule `[^\n\r:]` either as a token or as a whitespace category, depending on the context which the rule defines.

**Comment by mengzhuo** [comment]
I see, it seems that Golang/exp/ebnf
 https://github.com/golang/exp/blob/master/ebnf/ebnf.go#L89
Implement a Range dialect of EBNF
